# Generated by Django 2.1.2 on 2018-11-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idmascota', models.AutoField(primary_key=True, serialize=False)),
                ('nomascota', models.CharField(max_length=30)),
            ],
        ),
    ]
