# Generated by Django 2.1.2 on 2018-11-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perris', '0002_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='descripcion',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='mascota',
            name='estado',
            field=models.CharField(default='Rescatado', max_length=20),
        ),
        migrations.AddField(
            model_name='mascota',
            name='raza',
            field=models.CharField(default='SOME STRING', max_length=20),
        ),
    ]
