# Generated by Django 2.1.2 on 2018-11-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perris', '0004_auto_20181107_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(default='Mascota', max_length=20),
        ),
    ]
