# Generated by Django 2.1.2 on 2018-11-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perris', '0006_auto_20181109_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='nomascota',
            field=models.CharField(max_length=30, verbose_name='Nombre Mascota'),
        ),
    ]
