# Generated by Django 2.1.2 on 2018-11-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perris', '0007_auto_20181109_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='document',
            field=models.ImageField(default='', upload_to='fotos/'),
        ),
    ]
