# Generated by Django 2.1.2 on 2018-11-12 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perris', '0008_mascota_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='document',
            new_name='fotografia',
        ),
    ]
